export const SHOWMSG_MSG_SUCCESS = 'SHOWMSG_MSG_SUCCESS';
export const SHOWMSG_MSG_DANGER = 'SHOWMSG_MSG_DANGER';
export const SHOWMSG_RESET = 'SHOWMSG_RESET';
export const LOADING = 'LOADING';
export const UPDATEINFO = 'UPDATEINFO';
export const REDIRECT = 'REDIRECT';
export const REFRESH = 'REFRESH';
export const UPDATEMSGCOUNT = 'UPDATEMSGCOUNT';