const lang = {
    why_us: "لماذا نحن",
    jobs: 'Jobs AR',
    talent: 'Talent AR',
    blog: 'Blog AR',
    contact_us: 'Contact Us AR',
    login: 'Login AR',
    register: 'Register AR',
    log_in: 'Log In AR',
    create_an_account: 'Create an Account AR',
    profile: 'Profile AR',
    logout: 'Logout AR',
    services: 'Services AR',
    dashboard: 'Dashboard AR',
    follow_us_on_social: 'Follow us on social AR',
    terms_and_conditions: 'Terms and Conditions AR',
    data_protection: 'Data Protection AR',
    information: 'Information AR',
    about: 'About AR',
    get_in_touch: 'Get in touch AR',
    copyright_2020: '© Copyright 2020 AR',
    phone: '+961 3 067 205 AR',
    email: 'info@devalopers.com AR',
    tech_focused_platform: 'Tech-Focused AR',
    free: '100% Free AR',
    community_focused: 'Community-Focused AR',
    privacy_parag_one: 'DEVALOPERS ("us", "we", or "our") operates the https://DEVALOPERS.com/ website (the "Service"). AR',
    privacy_policy: 'Privacy Policy AR',
    privacy_policy_effective_date: 'Effective date: June 01, 2020 AR',
    terms_header: 'Terms',
    terms:'Terms & Conditions',
    terms_last_updated:'Last updated: June 01, 2020 AR',
    no_messages: 'No messages yet, people will start contacting you soon AR',
    no_applicants: 'No applicants yet AR',
    developer: 'Developer',
    ux_expert_and_designer: 'UX Expert and Designer AR',
    technical_product_manager: 'Technical Product Manager AR',
    technical_project_manager: 'Technical Project Manager AR',
    data_scientists_ai_ml_experts: 'Data Scientists (AI / ML Experts AR)',
    hire_software: 'Software AR',
    hire_developers: 'Developers AR',
    hire_ui_ux: 'UI/UX AR',
    hire_experts:' Experts AR',
    hire_technical_product_projects_managers: 'Technical Product & Projects Managers AR',
    hire_data_scientists: 'Data Scientists AR',
    hire_ai_ml_experts: '(AI & ML Experts) AR',
    label_website: "Website AR",
    label_location: "Location AR",
    label_description: "Description AR",
    no_description: "No Description AR",
    label_rate: "Rate AR",
    label_facebook: "Facebook AR",
    label_linkedin: "Linkedin AR",
    label_github: "Github AR",
    label_placeholder_website: 'website AR',
    label_placeholder_location: 'location AR',
    label_placeholder_description: 'description AR',
    label_placeholder_rate: 'rate AR',
    label_placeholder_facebook: 'facebook AR',
    label_placeholder_linkedin: 'linkedin AR',
    label_placeholder_github: 'github AR',
    label_company_name: 'Company Name AR',
    label_company_type: 'Company Type AR',
    label_description: 'Description AR',
    label_placeholder_company_name: 'Company Name AR',
    label_placeholder_company_type: 'Company Type AR',
    label_placeholder_description: 'Description AR',
    list_it_industry: 'IT Industry AR',
    list_web_mobile: 'Web & Mobile AR',
    list_web_solution: 'Web Solution AR',
    no_salary: 'No Salary Set AR',
    agree_to: 'I agree to the AR',
    search_talent: 'Search talents by skill AR',
}
export default lang;