const lang = {
    why_us: 'Why us',
    jobs: 'Jobs',
    talent: 'Talents',
    blog: 'Blog',
    contact_us: 'Contact Us',
    login: 'Login',
    register: 'Register',
    log_in: 'Log In',
    create_an_account: 'Create an Account',
    profile: 'Profile',
    logout: 'Logout',
    services: 'Services',
    dashboard: 'Dashboard',
    follow_us_on_social: 'Follow us on social media',
    terms_and_conditions: 'Terms and Conditions',
    data_protection: 'Data Protection',
    information: 'Information',
    about: 'About',
    get_in_touch: 'Get in touch',
    testimonials: 'Testimonials',
    post_jobs: 'Post Jobs',
    hire_talents: 'Hire Talents',
    most_searched_skills: 'Most searched skills',
    most_active_companies: 'Most active companies',
    copyright_2020: '© Copyright 2020',
    phone: '+961 3 067 205',
    email: 'info@devalopers.com',
    tech_focused_platform: 'Tech-Focused',
    free: '100% Free',
    community_focused: 'Community-Focused',
    privacy_parag_one: 'DEVALOPERS ("us", "we", or "our") operates the https://DEVALOPERS.com/ website (the "Service").',
    privacy_policy: 'Privacy Policy',
    privacy_policy_effective_date: 'Effective date: June 01, 2020',
    terms_header: 'Terms',
    terms:'Terms & Conditions',
    terms_last_updated:'Last updated: June 01, 2020',
    no_messages: 'No messages yet, people will start contacting you soon',
    no_applicants: 'No applicants yet',
    developer: 'Developer',
    ux_expert_and_designer: 'UX Expert and Designer',
    technical_product_manager: 'Technical Product Manager',
    technical_project_manager: 'Technical Project Manager',
    data_scientists_ai_ml_experts: 'Data Scientists (AI / ML Experts)',
    hire_software: 'Software',
    hire_developers: 'Developers',
    hire_ui_ux: 'UI/UX',
    hire_experts:' Experts',
    hire_technical_product_projects_managers: 'Technical Product & Projects Managers',
    hire_data_scientists: 'Data Scientists',
    hire_ai_ml_experts: 'AI & ML Experts',
    label_website: "Website",
    label_location: "Location",
    label_description: "Description",
    no_description: "No Description",
    label_rate: "Rate",
    label_facebook: "Facebook",
    label_linkedin: "Linkedin",
    label_github: "Github",
    label_placeholder_website: 'website',
    label_placeholder_location: 'location',
    label_placeholder_description: 'description',
    label_placeholder_rate: 'rate',
    label_placeholder_facebook: 'facebook',
    label_placeholder_linkedin: 'linkedin',
    label_placeholder_github: 'github',
    label_company_name: 'Company Name',
    label_company_type: 'Company Type',
    label_description: 'Description',
    label_placeholder_company_name: 'Company Name',
    label_placeholder_company_type: 'Company Type',
    label_placeholder_description: 'Description',
    list_it_industry: 'IT Industry',
    list_web_mobile: 'Web & Mobile',
    list_web_solution: 'Web Solution',
    no_salary: 'No Salary Set',
    agree_to: 'I agree to the',
    search_talent: 'Search talents by skill',
}

export default lang;